src/main/java/N1/entity/ChiTietHoaDon.java
package N1.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
@IdClass(ChiTietHoaDonPK.class)
public class ChiTietHoaDon implements Serializable {
    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "maHD", columnDefinition = "INT")
    private HoaDon hoaDon;

    @Id
    @JoinColumn(name = "maSp", columnDefinition = "INT")
    @ManyToOne(fetch = FetchType.EAGER)
    private SanPham sanPham;

    @Column(name = "soLuong", nullable = false, columnDefinition = "INT DEFAULT(1) CHECK(soLuong >= 1)")
    private int soLuong;

    @Column(name = "giaBan", nullable = false, columnDefinition = "MONEY DEFAULT(0) CHECK(giaBan >= 0)")
    private double giaBan;

    public ChiTietHoaDon() {
    }

    public ChiTietHoaDon(HoaDon hoaDon, SanPham sanPham, int soLuong, double giaBan) {
		this.hoaDon = hoaDon;
		this.sanPham = sanPham;
		this.soLuong = soLuong;
		this.giaBan = giaBan;
	}

	public ChiTietHoaDon(SanPham sanPham, int soLuong, double giaBan) {
        this.sanPham = sanPham;
        this.soLuong = soLuong;
        this.giaBan = giaBan;
    }

    public SanPham getSanPham() {
        return sanPham;
    }

    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }

    public int getSoLuong() {
        return soLuong;
    }

    public void setSoLuong(int soLuong) {
        this.soLuong = soLuong;
    }

    public double getThanhTien() {
        return this.giaBan * this.soLuong;
    }

	public HoaDon getHoaDon() {
		return hoaDon;
	}

	public void setHoaDon(HoaDon hoaDon) {
		this.hoaDon = hoaDon;
	}

	public double getGiaBan() {
		return giaBan;
	}

	public void setGiaBan(double giaBan) {
		this.giaBan = giaBan;
	}

	@Override
	public String toString() {
		return "ChiTietHoaDon [sanPham=" + sanPham.getMaSp() + ", soLuong=" + soLuong + ", giaBan="
				+ giaBan + "]";
	}
}

src/main/java/N1/Controller/LoginController.java
package N1.Controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class LoginController {

	@GetMapping({"/dang-nhap", "/login"})
	public String showLoginPage(Model model) {
		return "user/login";
	}

}

src/main/java/N1/Controller/RegistrationController.java
package N1.Controller;

import java.util.logging.Logger;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.propertyeditors.StringTrimmerEditor;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.provisioning.UserDetailsManager;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.InitBinder;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import N1.Service.*;
import N1.entity.*;

@Controller
@RequestMapping("/dang-ky")
public class RegistrationController {
	@Autowired
	private TaiKhoanService taiKhoanService;
	@Autowired
	private UserDetailsManager userDetailsManager;

	private PasswordEncoder passwordEncoder = new BCryptPasswordEncoder();
	private Logger logger = Logger.getLogger(getClass().getName());

	@InitBinder
	public void initBinder(WebDataBinder dataBinder) {
		StringTrimmerEditor stringTrimmerEditor = new StringTrimmerEditor(true);
		dataBinder.registerCustomEditor(String.class, stringTrimmerEditor);
	}

	@GetMapping("")
	public String showRegistrationForm(Model theModel) {
		theModel.addAttribute("crmUser", new TaiKhoan());
		return "user/registration";

	}

	@PostMapping("/processRegistrationForm")
	public String processRegistrationForm(
			@Valid @ModelAttribute("crmUser") TaiKhoan theCrmUser,
			BindingResult theBindingResult,
			Model theModel) {

		String tenDangNhap = theCrmUser.getTenDangNhap();
		logger.info("Processing registration form for: " + tenDangNhap);

		if (theBindingResult.hasErrors()) {
			theModel.addAttribute("crmUser", new TaiKhoan());
			theModel.addAttribute("registrationError", "User name/password can not be empty.");
			logger.warning("User name/password can not be empty.");

			return "user/registration";
		}

		boolean userExitst = taiKhoanService.doesUserExist(tenDangNhap);
		System.out.println(userExitst);
		if (userExitst) {
			theModel.addAttribute("crmUser", new TaiKhoan());
			theModel.addAttribute("registrationError", "Email đã được đăng ký.");
			logger.warning("Email đã được đăng ký.");

			return "user/registration";
		}

		String encodedPassword = passwordEncoder.encode(theCrmUser.getMatKhau());

		encodedPassword = "{bcrypt}" + encodedPassword;
		System.out.println(encodedPassword);
		
		NguoiDung user = new NguoiDung();
		theCrmUser.setMatKhau(encodedPassword);
		user.setTaiKhoan(theCrmUser);
		user.setTenND(tenDangNhap);
		
		taiKhoanService.createUser(user);

		return "redirect:/dang-nhap";
	}

	private boolean doesUserExist(String tenDangNhap) {

		logger.info("Checking if user exists: " + tenDangNhap);

		// check the database if the user already exists
		boolean exists = userDetailsManager.userExists(tenDangNhap);

		logger.info("User: " + tenDangNhap + ", exists: " + exists);

		return exists;
	}

}

src/main/java/N1/Controller/UserController.java
package N1.Controller;

import java.security.Principal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import N1.DTO.*;
import N1.Service.*;
import N1.entity.*;
import N1.utils.Datetime;

@Controller
@RequestMapping("/user")
public class UserController {
	@Autowired
	private SanPhamService sanPhamService;
	@Autowired
	private NguoiDungService nguoiDungService;
	@Autowired
	private LoaiSanPhamService loaiSanPhamService;
	@Autowired
	private HoaDonService hoaDonService;
	@Autowired
	private GioHangService gioHangService;
	@Autowired
	private CTHoaDonService ctHoaDonService;
	@Autowired
	private TaiKhoanService taiKhoanService;
	
	@RequestMapping(value = { "/gio-hang", "/cart" }, method = RequestMethod.GET)
	public String showShoppingCartPage(Model model) {
		String returnUrl = "";
		returnUrl = "redirect:/dang-nhap";
		
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		NguoiDung nguoiDung = new NguoiDung(); 
		int soLuongSpGh = 0;
		if (authentication != null && authentication.getPrincipal() instanceof UserDetails) {
			model.addAttribute("isCategoryPage", 0);
			String email = authentication.getName();
			nguoiDung = nguoiDungService.findNguoiDungByEmail(email);
			soLuongSpGh = gioHangService.getNumOfSanPhamInGioHangByEmail(email);
			model.addAttribute("nguoiDung", nguoiDung);
			model.addAttribute("soLuongSpGh", soLuongSpGh);
			
			int maND = nguoiDung.getMaND();
			List<GioHang> gioHang = gioHangService.findGioHangByUserId(maND);
			double tongTien = 0;
			for (GioHang gioHang2 : gioHang) {
				tongTien += gioHang2.getSanPham().getGiaSP() * gioHang2.getSoLuong() *
						(100 - gioHang2.getSanPham().getGiamGia()) / 100;
			}
			model.addAttribute("tongTien", tongTien);
			
			List<LoaiSanPham> dsLoaiSanPham = loaiSanPhamService.findAll();
			model.addAttribute("dsLoaiSanPham", dsLoaiSanPham);
			
			List<GioHang> dsGioHang = gioHangService.findGioHangByUserId(maND);
			model.addAttribute("dsSanPhamGioHang", dsGioHang);
			returnUrl = "user/shopping-cart";
		}

		return returnUrl;
	}
	
	@PostMapping(value = { "/gio-hang/id={id}", "/cart/id={id}" })
	public String deleteShoppingCartById(Model model, @PathVariable(name = "id", required = false) Integer idSanPham) {
		String returnUrl = "";
		returnUrl = "redirect:/dang-nhap";
		
		Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
		NguoiDung nguoiDung = new NguoiDung(); 
		if (authentication != null && authentication.getPrincipal() instanceof UserDetails) {
			String email = authentication.getName();
			nguoiDung = nguoiDungService.findNguoiDungByEmail(email);
			model.addAttribute("nguoiDung", nguoiDung);
			
			if (idSanPham != null || idSanPham > 0) {
				gioHangService.deleteGioHangByIdNguoiDungAndIdSanPham(nguoiDung.getMaND(), idSanPham);
			}
			
			returnUrl = "redirect:/user/gio-hang";
		}

		return returnUrl;
	}
  
	@PostMapping({ "/gio-hang", "/cart" })
	public String addOrUpdateOrder(Principal principal,
			@RequestParam(name = "dscthdmaSp", required = false) List<Integer> dscthdmaSp,
			@RequestParam(name = "dscthdsoLuong", required = false) List<Integer> dscthdsoLuong, 
			Model model, HttpServletRequest request, RedirectAttributes redirectAttributes) {
		
		
		if(dscthdmaSp == null) {
			dscthdmaSp = new ArrayList<Integer>();
			dscthdsoLuong = new ArrayList<Integer>();
		}

		NguoiDung user = nguoiDungService.findNguoiDungByEmail(principal.getName());
		
		
		List<GioHang> dsGioHang = new ArrayList<GioHang>();
		for(int i=0; i<dscthdmaSp.size(); i++) {
			SanPham sanPham = sanPhamService.getSanPhamByIdSanPham(dscthdmaSp.get(i));
			dsGioHang.add(new GioHang(user, sanPham, dscthdsoLuong.get(i)));
		}
		System.out.println(dsGioHang);
		gioHangService.updateDanhSachGioHang(user.getMaND(), dsGioHang);
		return "redirect:/user/gio-hang";
	}
	
	@RequestMapping({ "/thanh-toan", "/checkout" })
	public String showCheckoutPage(Model model) {
		Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		String username = "";
		if (principal instanceof UserDetails) {
			username = ((UserDetails) principal).getUsername();
		} else {
			username = principal.toString();
		}
		NguoiDung nguoiDung = nguoiDungService.findNguoiDungByEmail(username);
		int soLuongSpGh = gioHangService.getNumOfSanPhamInGioHangByEmail(username);
		model.addAttribute("soLuongSpGh", soLuongSpGh);
		List<LoaiSanPham> dsLoaiSanPham = loaiSanPhamService.findAll();
		model.addAttribute("dsLoaiSanPham", dsLoaiSanPham);
		// NguoiDung nguoiDung = nguoiDungService.findNguoiDungById(maND);
		model.addAttribute("nguoiDung", nguoiDung);

		List<SanPhamMua> dsSanPhamMua = sanPhamService.getSanPhamMua(nguoiDung.getMaND());
		int soLuong = dsSanPhamMua.size();
		model.addAttribute("dsSanPhamMua", dsSanPhamMua);

		model.addAttribute("soLuong", soLuong);

		double tongTienHang = 0;
		for (SanPhamMua sanPhamMua : dsSanPhamMua) {
			tongTienHang += sanPhamMua.getThanhTien();
		}

		double giamGia = tongTienHang * 0.05;
		double tongThanhToan = tongTienHang - giamGia;
		model.addAttribute("tongTienHang", tongTienHang);
		model.addAttribute("giamGia", giamGia);
		model.addAttribute("tongThanhToan", tongThanhToan);
		model.addAttribute("isCategoryPage", 0);

		return "user/checkout";
	}

	@RequestMapping(value = "/orders/success", method = RequestMethod.POST)
	public String createHoaDon(PayLoadCreateOrder payLoadCreateOrder, Model model, Principal principal) {
		model.addAttribute("isCategoryPage", 0);

		String username = "";
		if (principal != null) {
			username = principal.getName();
		}
		int soLuongSpGh = gioHangService.getNumOfSanPhamInGioHangByEmail(username);
		model.addAttribute("soLuongSpGh", soLuongSpGh);

		List<LoaiSanPham> dsLoaiSanPham = loaiSanPhamService.findAll();
		model.addAttribute("dsLoaiSanPham", dsLoaiSanPham);
		String diaChi = payLoadCreateOrder.getDiaChi();
		// 1 Lay user tu context security
		// 1.1 lay chi tiet user
		NguoiDung nguoiDung = nguoiDungService.findNguoiDungByEmail(username);
		// 2 Lay thong tin gio hang tu user
		List<ChiTietHoaDon> chiTietHoaDons = new ArrayList<ChiTietHoaDon>();
		List<SanPhamMua> dsSanPhamMua = sanPhamService.getSanPhamMua(nguoiDung.getMaND());
		// có danh sách sản phẩm mua -> mã sp, số lượng , thành tiền
		double tongTienHang = 0;
		int tongSoLuong = 0;
		for (SanPhamMua sanPhamMua : dsSanPhamMua) {
			tongTienHang += sanPhamMua.getThanhTien();
			tongSoLuong += sanPhamMua.getSoLuong();
		}
		double tongThanhToan = tongTienHang - tongTienHang * 0.05;
		// 3 Tien hanh tao hoa don, tao chi tiet hoa don-> Luu thanh cong
		Date ngayLHD = new Date();
		Date ngayGiaoHang = new Date(ngayLHD.getTime() + (3 * 1000 * 60 * 60 * 24));
		String trangThaiDonHang = "Chưa thanh toán";
		HoaDon hoaDon = new HoaDon(ngayLHD, tongThanhToan, tongSoLuong, trangThaiDonHang, ngayGiaoHang, diaChi,
				nguoiDung);
		HoaDon hoadonSave = hoaDonService.addHoaDon(hoaDon);
		dsSanPhamMua.forEach(e -> {
			SanPham sanPham = sanPhamService.getSanPhamByIdSanPham(e.getMaSp());
			ChiTietHoaDon cthd = new ChiTietHoaDon(hoadonSave, sanPham, e.getSoLuong(), e.getGiaSp());
			ctHoaDonService.addChiTietHoaDon(cthd);
			chiTietHoaDons.add(cthd);
		});
		// 4 Xoa gio hang cua khach hang
		gioHangService.deleteGioHangByIdNguoiDung(nguoiDung.getMaND());
		// 5 Tao trang chi tiet hoa don( truyen du lieu hoa don vua tao duoc qua trang
		// do)
		model.addAttribute("hoadonThanhToan", hoadonSave);
		model.addAttribute("chiTietHoaDons", chiTietHoaDons);
		model.addAttribute("tongTienHang", tongTienHang);
		model.addAttribute("giamGia", tongTienHang * 0.05);
		return "user/detail-order";
	}

	@RequestMapping(value = { "/show-order" })
	public String showHoaDonChiTiet(@RequestParam("maHD") int maHD, Model model, Principal principal) {
		NguoiDung nguoiDungLogin = new NguoiDung();
		int soLuongSpGh = 0;
		if (principal != null) {
			String email = principal.getName();
			nguoiDungLogin = nguoiDungService.findNguoiDungByEmail(email);
			soLuongSpGh = gioHangService.getNumOfSanPhamInGioHangByEmail(email);
		}
		model.addAttribute("nguoiDung", nguoiDungLogin);
		model.addAttribute("soLuongSpGh", soLuongSpGh);

		List<LoaiSanPham> dsLoaiSanPham = loaiSanPhamService.findAll();
		model.addAttribute("dsLoaiSanPham", dsLoaiSanPham);
		// Tìm hóa đơn theo mã hóa đơn
		System.out.println("maHD" + maHD);
		HoaDon hoaDon = hoaDonService.findHoaDonById(maHD);
		System.out.println(hoaDon.toString());
		List<ChiTietHoaDon> cthds = new ArrayList<ChiTietHoaDon>();
		cthds = ctHoaDonService.getDSCTHoaDonByMaHD(hoaDon.getMaHD());
		double tongTienHang = 0;
		for (ChiTietHoaDon chiTietHoaDon : cthds) {
			tongTienHang = tongTienHang + chiTietHoaDon.getThanhTien();
		}
		model.addAttribute("hoadonThanhToan", hoaDon);
		model.addAttribute("chiTietHoaDons", cthds);
		model.addAttribute("tongTienHang", tongTienHang);

src/main/webapp/WEB-INF/view/user/access-denied.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - 404</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="<c:url value = '/resources/admin/css/sb-admin-2.min.css'/>" rel="stylesheet">
	<style>
		body{
			background-color: #f8f9fc!important;
		}
		
		.bg-white{
			background-color: #f8f9fc!important;
			position: fixed;
		    bottom: 0;
		    transform: translateX(-50%);
		    left: 50%;
		}
		
		#content{
			position: absolute;
		    top: 50%;
		    left: 50%;
		    transform: translate(-50%, -50%);
		}
	</style>
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- 404 Error Text -->
                    <div class="text-center">
                        <div class="error mx-auto" data-text="404">404</div>
                        <p class="lead text-gray-800 mb-5">Trang không tồn tại hoặc bạn không có quyền truy cập trang này</p>
                        <a style="color: #7fad39" href="${pageContext.request.contextPath}/">&larr; Trở về trang chủ</a>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <jsp:include page="../admin/common/footer.jsp"></jsp:include>

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->


    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

src/main/webapp/WEB-INF/view/user/checkout.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<!DOCTYPE html>
<html lang="vi">

<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="ie=edge;charset="UTF-8" />
<title>Thanh toán</title>

<jsp:include page="./module/link-css.jsp" />
<style type="text/css">
.tb-hoadon {
	font-size: 14px;
}

.tb-header {
	width: 25%;
}
</style>
<script type="text/javascript">
	function validateAddressNotNull() {
		var a = document.getElementById("input_address");
		console.log("a>> ", a);
		if (a.value === null || a.value === '') {
			a.style.border = "1px solid red";
			return false;
		}
		a.style.border = "1px solid #ebebeb";
		return true;
	};

	function submicForm() {
		event.preventDefault();
		const validate = validateAddressNotNull();
		if (validate == false)
			return;
		event.currentTarget.submit();
	}
</script>
</head>

<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Humberger Begin -->
	<jsp:include page="./module/header-mobile.jsp">
		<jsp:param name="activePage" value="shoppingCart" />
		<jsp:param name="soLuong" value="${soLuong}" />
		<jsp:param name="tongTienHang" value="${tongTienHang}" />
	</jsp:include>
	<!-- Humberger End -->

	<!-- Header Section Begin -->
	<jsp:include page="./module/header.jsp">
		<jsp:param name="activePage" value="shoppingCart" />
		<jsp:param name="soLuong" value="${soLuong}" />
		<jsp:param name="tongTienHang" value="${tongTienHang}" />
	</jsp:include>
	<!-- Header Section End -->

	<!-- Header Section End -->

	<!-- Search bar Begin -->
	<jsp:include page="./module/search-bar.jsp">
		<jsp:param name="showBanner" value="false" />
	</jsp:include>

	<!-- Breadcrumb Section Begin -->
	<!-- Breadcrumb Section End -->

	<!-- Checkout Section Begin -->

	<c:if test="${dsSanPhamMua.size()==0 }">
		<div style="text-align: center;" class="mb-4">
			<p>Giỏ hàng rỗng</p>
			<a style="color: #326e51; background-color: transparent;"
				href='<c:url value = "/trang-chu" />'>Tiếp
				tục mua hàng <i class="fa fa-shopping-cart" aria-hidden="true"></i>
			</a>
		</div>
	</c:if>

	<c:if test="${dsSanPhamMua.size()!=0 }">
		<section class="checkout spad">
			<div class="container">
				<div class="checkout__form">
					<c:url var="toUrl"
						value="/user/orders/success">
						
					</c:url>
					<form:form id="form-create-order" action="${toUrl}" method="post"
						onsubmit="return submicForm()">
						<div class="row">
							<div class="col-lg-8 col-md-6">
								<div class="row">
									<div class="col-lg-6">
										<div class="checkout__input">
											<p>
												Tên<span>*</span>
											</p>
											<input type="text" readonly="readonly"
												value="${fn:substring(nguoiDung.tenND,fn:split(nguoiDung.tenND, ' ')[0].length() + 1, 500)}" />
										</div>
									</div>
									<div class="col-lg-6">
										<div class="checkout__input">
											<p>
												Họ<span>*</span>
											</p>
											<input type="text" readonly="readonly"
												value="${fn:split(nguoiDung.tenND, ' ')[0]}" />
										</div>
									</div>
								</div>
								<div class="checkout__input">
									<p>
										Số điện thoại<span>*</span>
									</p>
									<input type="text" readonly="readonly" name="sdt"
										value="${nguoiDung.sdt }" />
								</div>
								<div class="checkout__input">
									<p>
										Email<span>*</span>
									</p>
									<input type="text" readonly="readonly" name="taiKhoan"
										value="${nguoiDung.taiKhoan.tenDangNhap }" />
								</div>
								<div class="checkout__input">
									<p>
										Địa chỉ<span>*</span>
									</p>
									<input id="input_address" name="diaChi" path="diaChi"
										style="font-family: 'Roboto', sans-serif;" type="text"
										placeholder="Địa chỉ của bạn ..." class="checkout__input__add"
										onkeyUp="validateAddressNotNull()" value="${nguoiDung.diaChi}" />
								</div>
								<div class="checkout__input">
									<p>
										Ghi chú đơn hàng<span>*</span>
									</p>
									<input type="text"
										placeholder="Ghi chú về đơn hàng của bạn, Ví dụ như ghi chú đặc biệt cho đơn hàng" />
								</div>
							</div>
							<div class="col-lg-4 col-md-6">
								<div class="checkout__order">
									<h4>Đơn hàng của bạn</h4>
									<table style="width: 100%" class="tb-hoadon">
										<tr>
											<th class="tb-header">Sản phẩm</th>
											<th class="tb-header">Giá thành</th>
											<th class="tb-header">Số lượng</th>
											<th class="tb-header">Thành tiền</th>
										</tr>
										<c:forEach var="sanPhamMua" items="${dsSanPhamMua }">
											<tr>
												<td>${sanPhamMua.tenSp}</td>
												<td><fmt:formatNumber value="${sanPhamMua.giaSp}"
														type="currency" currencySymbol="" />đ</td>
												<td>${sanPhamMua.soLuong}</td>
												<td><fmt:formatNumber value="${sanPhamMua.thanhTien}"
														type="currency" currencySymbol="" />đ</td>

											</tr>
										</c:forEach>


									</table>

									<div class="checkout__order__subtotal">
										Tổng tiền hàng <span> <c:out value="${tongTienHang}"></c:out></span>

									</div>
									<div class="row">
										<div class="col-8">Giảm giá</div>
										<div class="col-4 text-right">
											<div class="checkout__order__subtotal"
												style="border: none; padding-top: 0; font-weight: normal">
												<span> -<c:out value="${giamGia}"></c:out>

												</span>
											</div>

										</div>
									</div>
									<div class="checkout__order__total">
										Tổng thanh toán <strong style="float: right; color:#dd2222;" >

											<fmt:formatNumber value="${tongThanhToan}" type="currency"
												currencySymbol="" />đ

										</strong>
									</div>
									<button type="submit" class="site-btn">Đặt hàng</button>
								</div>
							</div>
						</div>
					</form:form>
				</div>
			</div>
		</section>
	</c:if>

	<!-- Checkout Section End -->

	<!-- Footer Section Begin -->
	<jsp:include page="./module/footer.jsp" />
	<!-- Footer Section End -->

	<!-- Js Plugins -->
	<jsp:include page="./module/link-js.jsp" />
</body>

</html>

src/main/webapp/WEB-INF/view/user/registration-confirmation.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<html>

    <head>
        <title>Registration Confirmation</title>
    </head>

    <body>

        <h2>User registered successfully!</h2>

        <hr>

        <a href="${pageContext.request.contextPath}/login">Đăng nhập với tài khoản mới</a>

    </body>

</html>